### PR TITLE
a few corrections to some titles and angles on the quilt

### PR DESCRIPTION
**Pull request by jamesgorrie**
As proposed by Russel.
These still need to be built and deployed.

### CODE REVIEW

**Comment by jamesgorrie** [comment]
@stephenwf

**Comment by stephenwf** [comment]
👍  looks good, want me to merge and publish?

**Comment by jamesgorrie** [comment]
@stephenwf cheers, thanks for the help on this.

**Comment by stephenwf** [comment]
That should be it published now.

**Pull request merged**
